/* ============================================================
   16 · BazarBD — Marketplace Data
   ============================================================ */
const MP = Object.freeze({

  site: { name:'BazarBD', tagline:'Bangladesh\'s Multi-Vendor Marketplace', currency:'৳', year:2026 },

  currentUser: { id:'u1', name:'Tahsan Islam', email:'tahsan@email.com', phone:'+880 1711-000111', role:'buyer',
    addresses:[{id:'a1',label:'Home',name:'Tahsan Islam',phone:'+880 1711-000111',address:'42 Gulshan Ave',area:'Gulshan',district:'Dhaka',division:'Dhaka',zip:'1212',default:true}],
    wishlist:['p1','p5','p8'], recentlyViewed:['p1','p2','p3','p6'] },

  stats: { totalSellers:1200, totalProducts:45000, totalOrders:128000, activeUsers:35000, platformRevenue:18500000 },

  categories: [
    { id:'cat1', name:'Fashion',     icon:'👕', sub:['Men','Women','Kids','Accessories'] },
    { id:'cat2', name:'Electronics', icon:'📱', sub:['Phones','Laptops','Audio','Wearables'] },
    { id:'cat3', name:'Home & Living',icon:'🏠', sub:['Furniture','Kitchen','Decor','Bedding'] },
    { id:'cat4', name:'Books',       icon:'📚', sub:['Fiction','Academic','Tech','Bangla'] },
    { id:'cat5', name:'Gaming',      icon:'🎮', sub:['Consoles','PC','Accessories','Games'] },
    { id:'cat6', name:'Beauty',      icon:'💄', sub:['Skincare','Makeup','Fragrance','Hair'] },
    { id:'cat7', name:'Grocery',     icon:'🥗', sub:['Pantry','Snacks','Beverages','Fresh'] },
    { id:'cat8', name:'Sports',      icon:'⚽', sub:['Cricket','Football','Fitness','Outdoor'] }
  ],

  sellers: [
    { id:'s1', name:'TechBD',     logo:'TB', tagline:'Quality electronics at best prices', banner:'linear-gradient(135deg,#0EA5E9,#2563EB)',
      rating:4.8, reviews:1420, products:1200, followers:8500, since:'2023', verified:true, topRated:false,
      location:'Dhaka', category:'Electronics', revenue:4850000, orders:342,
      contact:{email:'support@techbd.com',phone:'+880 1711-111111'} },
    { id:'s2', name:'FashionX',   logo:'FX', tagline:'Trendy fashion for every occasion', banner:'linear-gradient(135deg,#EC4899,#F97316)',
      rating:4.7, reviews:980, products:850, followers:6200, since:'2023', verified:true, topRated:false,
      location:'Chittagong', category:'Fashion', revenue:3200000, orders:280,
      contact:{email:'hello@fashionx.com',phone:'+880 1811-222222'} },
    { id:'s3', name:'HomeNest',   logo:'HN', tagline:'Make your house a home', banner:'linear-gradient(135deg,#059669,#10B981)',
      rating:4.9, reviews:620, products:430, followers:3800, since:'2024', verified:true, topRated:true,
      location:'Dhaka', category:'Home & Living', revenue:2100000, orders:195,
      contact:{email:'care@homenest.com',phone:'+880 1911-333333'} },
    { id:'s4', name:'BookWorm',   logo:'BW', tagline:'Discover your next great read', banner:'linear-gradient(135deg,#7C3AED,#A855F7)',
      rating:4.6, reviews:340, products:2100, followers:4100, since:'2024', verified:true, topRated:false,
      location:'Rajshahi', category:'Books', revenue:980000, orders:520,
      contact:{email:'info@bookworm.com',phone:'+880 1611-444444'} },
    { id:'s5', name:'GameZone',   logo:'GZ', tagline:'Level up your gaming experience', banner:'linear-gradient(135deg,#DC2626,#F97316)',
      rating:4.5, reviews:210, products:380, followers:5600, since:'2025', verified:false, topRated:false,
      location:'Dhaka', category:'Gaming', revenue:1450000, orders:165,
      contact:{email:'play@gamezone.com',phone:'+880 1511-555555'} },
    { id:'s6', name:'GlowUp',    logo:'GU', tagline:'Glow from the inside out', banner:'linear-gradient(135deg,#F59E0B,#EC4899)',
      rating:4.8, reviews:450, products:620, followers:7200, since:'2024', verified:true, topRated:true,
      location:'Sylhet', category:'Beauty', revenue:1780000, orders:310,
      contact:{email:'beauty@glowup.com',phone:'+880 1411-666666'} }
  ],

  products: [
    { id:'p1', title:'ProSound Wireless X50', sellerId:'s1', category:'Electronics', sub:'Audio',
      price:3500, comparePrice:5000, images:['📷','📷','📷','📷'],
      colors:[{name:'Black',hex:'#111',stock:12},{name:'White',hex:'#F5F5F5',stock:5},{name:'Blue',hex:'#3B82F6',stock:0}],
      sizes:null, rating:4.3, reviewCount:128, sold:340,
      badge:'Sale', stock:17, description:'Premium wireless headphones with ANC, 40h battery, Bluetooth 5.3, and foldable design. Perfect for commuters and audiophiles alike.',
      specs:[['Brand','ProSound'],['Model','X50'],['Connectivity','Bluetooth 5.3'],['Battery','40 hours'],['Weight','250g'],['ANC','Yes'],['Driver','40mm'],['Warranty','1 year']],
      shipping:{standard:80,express:150,days:'3-5'},
      returns:'7-day return policy' },
    { id:'p2', title:'USB-C Fast Charging Cable 2m', sellerId:'s1', category:'Electronics', sub:'Accessories',
      price:350, comparePrice:500, images:['📷','📷'],
      colors:[{name:'Black',hex:'#111',stock:200},{name:'White',hex:'#F5F5F5',stock:150}],
      sizes:null, rating:4.7, reviewCount:210, sold:1850,
      badge:'Hot', stock:350, description:'Durable braided USB-C cable with 100W PD fast charging support. Compatible with all USB-C devices.',
      specs:[['Brand','TechBD'],['Length','2 meters'],['Material','Braided Nylon'],['Power','100W PD'],['Data','USB 3.1'],['Warranty','6 months']],
      shipping:{standard:60,express:120,days:'2-3'},
      returns:'7-day return policy' },
    { id:'p3', title:'Classic Leather Watch — Heritage Collection', sellerId:'s2', category:'Fashion', sub:'Accessories',
      price:5000, comparePrice:7500, images:['📷','📷','📷'],
      colors:[{name:'Brown',hex:'#8B4513',stock:8},{name:'Black',hex:'#111',stock:15},{name:'Tan',hex:'#D2B48C',stock:3}],
      sizes:null, rating:4.6, reviewCount:89, sold:120,
      badge:'Sale', stock:26, description:'Handcrafted genuine leather watch with Japanese Miyota movement. Water resistant, sapphire crystal glass.',
      specs:[['Brand','FashionX Heritage'],['Movement','Miyota Quartz'],['Case','42mm Stainless Steel'],['Water Resistance','3 ATM'],['Strap','Genuine Leather'],['Warranty','2 years']],
      shipping:{standard:100,express:200,days:'3-5'},
      returns:'14-day return policy' },
    { id:'p4', title:'Ergonomic Office Chair Pro', sellerId:'s3', category:'Home & Living', sub:'Furniture',
      price:15000, comparePrice:22000, images:['📷','📷','📷','📷'],
      colors:[{name:'Black',hex:'#111',stock:6},{name:'Gray',hex:'#6B7280',stock:4}],
      sizes:null, rating:4.9, reviewCount:45, sold:62,
      badge:'Sale', stock:10, description:'Premium ergonomic chair with adjustable lumbar support, 4D armrests, breathable mesh back, and 120° recline.',
      specs:[['Brand','HomeNest'],['Material','Mesh + Steel Frame'],['Max Weight','150kg'],['Adjustable Height','Yes'],['Recline','120°'],['Warranty','3 years']],
      shipping:{standard:200,express:400,days:'5-7'},
      returns:'14-day return policy' },
    { id:'p5', title:'Bengali Short Stories Collection', sellerId:'s4', category:'Books', sub:'Bangla',
      price:450, comparePrice:600, images:['📷'],
      colors:null, sizes:null, rating:4.8, reviewCount:67, sold:280,
      badge:null, stock:85, description:'A curated anthology of the finest Bengali short stories from Rabindranath to modern authors. Hardcover edition.',
      specs:[['Author','Various'],['Publisher','BookWorm Press'],['Pages','384'],['Binding','Hardcover'],['Language','Bangla'],['ISBN','978-984-1234567']],
      shipping:{standard:60,express:100,days:'2-4'},
      returns:'7-day return policy' },
    { id:'p6', title:'RGB Mechanical Gaming Keyboard', sellerId:'s5', category:'Gaming', sub:'Accessories',
      price:4500, comparePrice:6000, images:['📷','📷','📷'],
      colors:[{name:'Black',hex:'#111',stock:20},{name:'White',hex:'#F5F5F5',stock:8}],
      sizes:null, rating:4.4, reviewCount:156, sold:410,
      badge:'Hot', stock:28, description:'Full-size mechanical keyboard with Cherry MX Blue switches, per-key RGB, and aluminum frame. N-key rollover.',
      specs:[['Brand','GameZone'],['Switch','Cherry MX Blue'],['Layout','Full-size 104 Key'],['Backlight','Per-key RGB'],['Connection','USB-C Wired'],['Frame','Aluminum'],['Warranty','2 years']],
      shipping:{standard:80,express:150,days:'3-5'},
      returns:'7-day return policy' },
    { id:'p7', title:'Vitamin C Brightening Serum 30ml', sellerId:'s6', category:'Beauty', sub:'Skincare',
      price:1200, comparePrice:1800, images:['📷','📷'],
      colors:null, sizes:[{name:'30ml',stock:45},{name:'50ml',stock:20,price:1800}],
      rating:4.7, reviewCount:312, sold:890,
      badge:'Hot', stock:65, description:'Potent 20% Vitamin C serum with Hyaluronic Acid and Niacinamide. Brightens, hydrates, and evens skin tone.',
      specs:[['Brand','GlowUp'],['Volume','30ml'],['Key Ingredients','Vitamin C 20%, Hyaluronic Acid, Niacinamide'],['Skin Type','All'],['Cruelty Free','Yes'],['Shelf Life','12 months']],
      shipping:{standard:60,express:100,days:'2-3'},
      returns:'No returns on opened products' },
    { id:'p8', title:'Slim Fit Polo Shirt — Premium Cotton', sellerId:'s2', category:'Fashion', sub:'Men',
      price:1500, comparePrice:2200, images:['📷','📷','📷'],
      colors:[{name:'Navy',hex:'#1E3A5F',stock:25},{name:'White',hex:'#F5F5F5',stock:18},{name:'Olive',hex:'#556B2F',stock:12}],
      sizes:[{name:'S',stock:10},{name:'M',stock:20},{name:'L',stock:15},{name:'XL',stock:10}],
      rating:4.5, reviewCount:94, sold:230,
      badge:'New', stock:55, description:'Premium 100% Supima cotton polo with a modern slim fit. Ribbed collar and cuffs, three-button placket.',
      specs:[['Brand','FashionX'],['Material','100% Supima Cotton'],['Fit','Slim'],['Collar','Ribbed'],['Care','Machine Washable'],['Origin','Bangladesh']],
      shipping:{standard:80,express:150,days:'3-5'},
      returns:'14-day return policy' },
    { id:'p9', title:'Cast Iron Dutch Oven 5.5L', sellerId:'s3', category:'Home & Living', sub:'Kitchen',
      price:3800, comparePrice:null, images:['📷','📷'],
      colors:[{name:'Red',hex:'#DC2626',stock:7},{name:'Black',hex:'#111',stock:12}],
      sizes:null, rating:4.8, reviewCount:38, sold:75,
      badge:null, stock:19, description:'Enameled cast iron Dutch oven for slow cooking, braising, and baking. Oven-safe to 260°C with self-basting lid.',
      specs:[['Brand','HomeNest'],['Capacity','5.5 Liters'],['Material','Enameled Cast Iron'],['Oven Safe','260°C'],['Dishwasher Safe','Yes'],['Weight','5.2kg']],
      shipping:{standard:150,express:300,days:'4-6'},
      returns:'14-day return policy' },
    { id:'p10', title:'Wireless Gaming Mouse — ProAim 7200', sellerId:'s5', category:'Gaming', sub:'Accessories',
      price:2800, comparePrice:3500, images:['📷','📷','📷'],
      colors:[{name:'Black',hex:'#111',stock:30},{name:'White',hex:'#F5F5F5',stock:15}],
      sizes:null, rating:4.6, reviewCount:98, sold:185,
      badge:'Sale', stock:45, description:'Ultra-lightweight 65g wireless gaming mouse. 7200 DPI optical sensor, 6 programmable buttons, 80h battery.',
      specs:[['Brand','GameZone'],['Sensor','7200 DPI Optical'],['Weight','65g'],['Battery','80 hours'],['Buttons','6 Programmable'],['Connection','2.4GHz Wireless + BT'],['Warranty','1 year']],
      shipping:{standard:80,express:150,days:'3-5'},
      returns:'7-day return policy' },
    { id:'p11', title:'BT Earbuds Pro — Active Noise Cancel', sellerId:'s1', category:'Electronics', sub:'Audio',
      price:2200, comparePrice:3000, images:['📷','📷','📷'],
      colors:[{name:'Black',hex:'#111',stock:3},{name:'White',hex:'#F5F5F5',stock:8}],
      sizes:null, rating:4.5, reviewCount:176, sold:520,
      badge:'Sale', stock:11, description:'True wireless earbuds with active noise cancellation, transparency mode, 28h total battery, and IPX5 water resistance.',
      specs:[['Brand','TechBD'],['Type','True Wireless'],['ANC','Yes'],['Battery','7h + 21h case'],['Water Resistance','IPX5'],['Bluetooth','5.3'],['Warranty','1 year']],
      shipping:{standard:60,express:120,days:'2-3'},
      returns:'7-day return policy' },
    { id:'p12', title:'Hydrating Face Moisturizer SPF30', sellerId:'s6', category:'Beauty', sub:'Skincare',
      price:950, comparePrice:1400, images:['📷','📷'],
      colors:null, sizes:[{name:'50ml',stock:55},{name:'100ml',stock:25,price:1600}],
      rating:4.6, reviewCount:188, sold:640,
      badge:null, stock:80, description:'Lightweight daily moisturizer with SPF30 protection, ceramides, and green tea extract. Non-greasy, suitable for all skin types.',
      specs:[['Brand','GlowUp'],['Volume','50ml'],['SPF','30'],['Key Ingredients','Ceramides, Green Tea, Hyaluronic Acid'],['Skin Type','All'],['Cruelty Free','Yes']],
      shipping:{standard:60,express:100,days:'2-3'},
      returns:'No returns on opened products' }
  ],

  flashDeals: [
    { productId:'p1', discount:30, endsAt:Date.now()+5*3600000 },
    { productId:'p3', discount:33, endsAt:Date.now()+5*3600000 },
    { productId:'p6', discount:25, endsAt:Date.now()+5*3600000 },
    { productId:'p10',discount:20, endsAt:Date.now()+5*3600000 },
    { productId:'p11',discount:27, endsAt:Date.now()+5*3600000 }
  ],

  reviews: [
    { id:'r1', productId:'p1', userId:'u2', name:'Nadia Rahman', rating:5, date:'2026-01-10', verified:true,
      text:'Amazing sound quality! The ANC is top-notch and battery lasts forever. Best purchase I\'ve made this year.',
      photos:['📷'], helpful:24, unhelpful:1, sellerReply:'Thank you Nadia! Glad you\'re enjoying the X50 🎧' },
    { id:'r2', productId:'p1', userId:'u3', name:'Arif Hossain', rating:4, date:'2026-01-08', verified:true,
      text:'Good headphones for the price. Comfortable for long use. Only issue is the mic could be better for calls.',
      photos:[], helpful:12, unhelpful:3, sellerReply:null },
    { id:'r3', productId:'p1', userId:'u4', name:'Sabrina Khan', rating:3, date:'2025-12-20', verified:true,
      text:'Decent sound but the build quality feels a bit plasticky. ANC works well though.',
      photos:['📷','📷'], helpful:8, unhelpful:5, sellerReply:'Hi Sabrina, sorry to hear that. Our newer batches have improved build quality.' },
    { id:'r4', productId:'p3', userId:'u5', name:'Rafi Ahmed', rating:5, date:'2026-01-12', verified:true,
      text:'Beautiful watch! The leather strap is incredibly soft and the movement is precise. Great gift option.',
      photos:['📷'], helpful:15, unhelpful:0, sellerReply:null },
    { id:'r5', productId:'p6', userId:'u6', name:'Imran Chowdhury', rating:5, date:'2026-01-05', verified:true,
      text:'Cherry MX Blues are amazing! The RGB lighting is bright and customizable. Build quality is solid.',
      photos:[], helpful:20, unhelpful:2, sellerReply:'Thanks Imran! Happy gaming! 🎮' },
    { id:'r6', productId:'p7', userId:'u7', name:'Fatima Begum', rating:4, date:'2025-12-28', verified:true,
      text:'Noticed visible brightening after 2 weeks of use. Texture is lightweight and absorbs quickly.',
      photos:['📷'], helpful:35, unhelpful:1, sellerReply:null },
    { id:'r7', productId:'p4', userId:'u8', name:'Kamal Uddin', rating:5, date:'2026-01-14', verified:true,
      text:'Best chair I\'ve ever owned. Back pain gone after a week. The lumbar support is incredible.',
      photos:[], helpful:42, unhelpful:0, sellerReply:'Wonderful to hear! Ergonomics matters. 💪' },
    { id:'r8', productId:'p8', userId:'u9', name:'Priya Das', rating:4, date:'2026-01-11', verified:true,
      text:'Great fit and fabric quality. The navy color is exactly as shown. Ordered 2 more!',
      photos:['📷'], helpful:9, unhelpful:1, sellerReply:null }
  ],

  orders: [
    { id:'ord1', number:'ORD-2026-0042', userId:'u1', date:'2026-01-15T10:30:00',
      status:'shipped', total:11950, discount:500, promoCode:'BAZARSAVE',
      address:{name:'Tahsan Islam',phone:'+880 1711-000111',address:'42 Gulshan Ave, Gulshan, Dhaka 1212'},
      payment:'bKash',
      shipments:[
        { sellerId:'s1', sellerName:'TechBD', status:'shipped', tracking:'TRK-BD-12345',
          method:'standard', shippingCost:80, estimatedDelivery:'Jan 18-20, 2026',
          items:[{productId:'p1',title:'ProSound Wireless X50',variant:'Black',qty:1,price:3500},
                 {productId:'p2',title:'USB-C Fast Charging Cable',variant:'Black',qty:2,price:350}] },
        { sellerId:'s2', sellerName:'FashionX', status:'processing', tracking:'TRK-BD-12346',
          method:'standard', shippingCost:100, estimatedDelivery:'Jan 19-21, 2026',
          items:[{productId:'p3',title:'Classic Leather Watch',variant:'Brown',qty:1,price:5000}] }
      ] },
    { id:'ord2', number:'ORD-2026-0038', userId:'u1', date:'2026-01-10T14:20:00',
      status:'delivered', total:5700, discount:0, promoCode:null,
      address:{name:'Tahsan Islam',phone:'+880 1711-000111',address:'42 Gulshan Ave, Gulshan, Dhaka 1212'},
      payment:'Nagad',
      shipments:[
        { sellerId:'s6', sellerName:'GlowUp', status:'delivered', tracking:'TRK-BD-11111',
          method:'express', shippingCost:100, estimatedDelivery:'Jan 11-12, 2026',
          items:[{productId:'p7',title:'Vitamin C Brightening Serum',variant:'30ml',qty:2,price:1200},
                 {productId:'p12',title:'Hydrating Face Moisturizer',variant:'50ml',qty:1,price:950}] },
        { sellerId:'s4', sellerName:'BookWorm', status:'delivered', tracking:'TRK-BD-11112',
          method:'standard', shippingCost:60, estimatedDelivery:'Jan 13-15, 2026',
          items:[{productId:'p5',title:'Bengali Short Stories Collection',variant:null,qty:2,price:450}] }
      ] }
  ],

  promoCodes: [
    { code:'BAZARSAVE', discount:500, type:'fixed', minOrder:5000, active:true },
    { code:'WELCOME10', discount:10, type:'percent', minOrder:1000, active:true },
    { code:'FREESHIP',  discount:0, type:'freeShipping', minOrder:3000, active:true }
  ],

  sellerTestimonials: [
    { name:'Rahim Khan', store:'TechBD', text:'Started with 10 products, now managing over 1,200. BazarBD gave us the platform to reach customers across Bangladesh.', revenue:'৳48,50,000' },
    { name:'Nusrat Jahan', store:'GlowUp', text:'The seller dashboard makes managing orders so easy. Our beauty brand grew 300% in just one year on BazarBD.', revenue:'৳17,80,000' }
  ],

  sellerRevenue30d: [
    {day:'Jan 1',amount:18000},{day:'Jan 2',amount:22000},{day:'Jan 3',amount:15000},
    {day:'Jan 4',amount:28000},{day:'Jan 5',amount:32000},{day:'Jan 6',amount:25000},
    {day:'Jan 7',amount:19000},{day:'Jan 8',amount:35000},{day:'Jan 9',amount:42000},
    {day:'Jan 10',amount:38000},{day:'Jan 11',amount:29000},{day:'Jan 12',amount:24000},
    {day:'Jan 13',amount:31000},{day:'Jan 14',amount:27000},{day:'Jan 15',amount:45000},
    {day:'Jan 16',amount:40000},{day:'Jan 17',amount:33000},{day:'Jan 18',amount:28000},
    {day:'Jan 19',amount:36000},{day:'Jan 20',amount:41000},{day:'Jan 21',amount:38000},
    {day:'Jan 22',amount:30000},{day:'Jan 23',amount:26000},{day:'Jan 24',amount:34000},
    {day:'Jan 25',amount:39000},{day:'Jan 26',amount:44000},{day:'Jan 27',amount:37000},
    {day:'Jan 28',amount:32000},{day:'Jan 29',amount:29000},{day:'Jan 30',amount:48000}
  ],

  platformRevenue30d: [
    {day:'Jan 1',amount:120000},{day:'Jan 2',amount:145000},{day:'Jan 3',amount:98000},
    {day:'Jan 4',amount:167000},{day:'Jan 5',amount:189000},{day:'Jan 6',amount:155000},
    {day:'Jan 7',amount:132000},{day:'Jan 8',amount:198000},{day:'Jan 9',amount:215000},
    {day:'Jan 10',amount:178000},{day:'Jan 11',amount:165000},{day:'Jan 12',amount:142000},
    {day:'Jan 13',amount:187000},{day:'Jan 14',amount:196000},{day:'Jan 15',amount:223000},
    {day:'Jan 16',amount:210000},{day:'Jan 17',amount:175000},{day:'Jan 18',amount:158000},
    {day:'Jan 19',amount:201000},{day:'Jan 20',amount:218000},{day:'Jan 21',amount:192000},
    {day:'Jan 22',amount:168000},{day:'Jan 23',amount:155000},{day:'Jan 24',amount:183000},
    {day:'Jan 25',amount:209000},{day:'Jan 26',amount:235000},{day:'Jan 27',amount:197000},
    {day:'Jan 28',amount:176000},{day:'Jan 29',amount:164000},{day:'Jan 30',amount:248000}
  ],

  divisions: ['Dhaka','Chittagong','Rajshahi','Sylhet','Khulna','Barisal','Rangpur','Mymensingh']
});
